# путь к файлу CSV, куда будут сохраняться лучше биды и аски
best_bid_ask_file_path: "best_bid_ask.csv"
# путь к файлу CSV, куда будут сохраняться трейды
trades_file_path: "trades.csv"
# задержка между запросами данных в секундах
delay: 1
# массив инструментов на бирже, по которым нужно собирать данные
# если пустой, будут собираться все инструменты, но осторожно их
# их более 2000 и все собираться будут долго.
symbols:
  - BTC/USDT
  # - ETH/USDT